### ISSUE TITLE
Enhance du API call

### ISSUE THREAD

**Issue by synfinatic** [mk23/webhdfs#32]
Add support for retrieving a specific summary field or an object of all data.
- [ ] implement a named tuple, i.e.

``` python
du(dirs=, files=, hdfs_usage=, disk_usage=, hdfs_quota=, disk_quota=)
```
- [ ] client
- [ ] docs
- [ ] shell
  - [ ] add du options to retrieve all summary parts

**Comment by mk23** [comment]
So we already do a GETCONTENTSUMMARY call as part of `du()`.  This could be extended to provide quota information.
